services:
  streamlit:
    build: .
    image: aqi-dashboard:latest
    user: root
    tty: true
    command: streamlit run /app/app.py --server.port=8501 --server.address=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./tif_output:/app/tif_output
      - ./app:/app
      - ./vertex-key.json:/app/vertex-key.json:ro
    ports:
      - "8501:8501"
    mem_limit: 1g
    memswap_limit: 2g
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - streamlit
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
